version: "3.3"

services:
  # MariaDB Database
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-defaultroot}
      MYSQL_DATABASE: gym_lockers
      MYSQL_USER: gym_user
      MYSQL_PASSWORD: ${DB_PASSWORD:-defaultpass}
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD:-defaultroot}"]
      timeout: 20s
      retries: 10

  # MQTT Broker (Mosquitto)
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt-config:/mosquitto/config
      - mqtt_data:/mosquitto/data
      - mqtt_logs:/mosquitto/log
    command: mosquitto -c /mosquitto/config/mosquitto.conf

  # Backend API
  backend:
    build:
      context: ./gym_lockers
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    depends_on:
      - db
      - mqtt
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: gym_user
      DB_PASSWORD: ${DB_PASSWORD:-defaultpass}
      DB_NAME: gym_lockers
      MQTT_HOST: mqtt
      MQTT_PORT: 1883
      MQTT_USERNAME: ${MQTT_USERNAME:-admin}
      MQTT_PASSWORD: ${MQTT_PASSWORD:-defaultmqtt}
    volumes:
      - ./gym_lockers/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Builder (Production)
  frontend-builder:
    build:
      context: ./gym_lockers/client
      dockerfile: Dockerfile.production
    volumes:
      - frontend_build:/usr/share/nginx/html

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend-builder
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_build:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:
    driver: local
  mqtt_data:
    driver: local
  mqtt_logs:
    driver: local
  frontend_build:
    driver: local
