name: "Gym Lockers Management System"
version: "1.2.6"
slug: "gym_lockers"
description: "A management system for gym lockers with MQTT support"
url: "https://github.com/Solace-Software/lockers"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
