name: "Gym Lockers Management System"
version: "1.2.0"
slug: "gym_lockers"
description: "A management system for gym lockers with MQTT support"
url: "https://github.com/Solace-Software/lockers"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
init: false
panel_icon: mdi:locker
panel_title: Gym Lockers
homeassistant_api: true
ingress: true
ingress_port: 3001

# Default values
options:
  database:
    host: ""
    port: 3306
    name: "gym_lockers"
    username: ""
    password: ""
  mqtt:
    use_internal: true
    external:
      host: ""
      port: 1883
      username: ""
      password: ""

# Schema for UI
schema:
  database:
    host: str
    port: port
    name: str
    username: str
    password: password
  mqtt:
    use_internal: bool
    external:
      host: str?
      port: port?
      username: str?
      password: password?

# UI Configuration
translations:
  en:
    title: "Gym Lockers"
    description: "Manage your gym lockers system"
    network:
      title: "Network"
      description: "Network configuration for the addon"
    database:
      title: "Database"
      description: "Configure your external MariaDB/MySQL database"
      host:
        name: "Host"
        description: "The hostname or IP address of your database server"
      port:
        name: "Port"
        description: "The port number of your database server (default: 3306)"
      name:
        name: "Database Name"
        description: "The name of the database to use"
      username:
        name: "Username"
        description: "Database user with necessary permissions"
      password:
        name: "Password"
        description: "Password for the database user"
    mqtt:
      title: "MQTT"
      description: "MQTT broker configuration"
      use_internal:
        name: "Use Internal Broker"
        description: "Use the built-in MQTT broker (recommended)"
      external:
        title: "External MQTT"
        description: "Configure external MQTT broker (if not using internal)"
        host:
          name: "Broker Host"
          description: "The hostname or IP address of your MQTT broker"
        port:
          name: "Broker Port"
          description: "The port number of your MQTT broker (default: 1883)"
        username:
          name: "Username"
          description: "MQTT broker username (optional)"
        password:
          name: "Password"
          description: "MQTT broker password (optional)"

# Panel configuration
panel_admin: true
webui: "http://[HOST]:[PORT:3001]"
ingress_stream: true

# Advanced configuration
stage: stable
hassio_role: default
hassio_api: true
auth_api: true
uart: false
map:
  - share:rw
  - ssl
  - config:rw