version: '3.8'

services:
  # All-in-One Gym Locker System
  gym-locker-system:
    image: gym-locker-dashboard:latest
    container_name: gym-locker-system
    restart: unless-stopped
    ports:
      - "3001:3001"  # Web interface
      - "1883:1883"  # MQTT broker
      - "9001:9001"  # MQTT WebSocket
      - "3306:3306"  # Database (optional, for external access)
    environment:
      # Database configuration (internal)
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=gym_admin
      - DB_PASSWORD=secure_password_123
      - DB_NAME=gym_lockers
      
      # MQTT configuration (internal)
      - MQTT_HOST=localhost
      - MQTT_PORT=1883
      - MQTT_USERNAME=gym_mqtt_user
      - MQTT_PASSWORD=mqtt_password_123
      - MQTT_CLIENT_ID=gym-admin-all-in-one
      
      # System settings
      - SYSTEM_AUTO_REFRESH=30
      - SYSTEM_DATA_RETENTION_DAYS=90
      - SYSTEM_BACKUP_ENABLED=true
      - SYSTEM_DEBUG_MODE=false
    volumes:
      - ./data:/app/data
      - ./mqtt-data:/mosquitto/data
      - ./mqtt-logs:/mosquitto/log
      - ./mqtt-config:/mosquitto/config
      - ./db-data:/var/lib/mysql
    networks:
      - gym-network
    depends_on:
      - mariadb
      - mosquitto

  # MariaDB Database (internal service)
  mariadb:
    image: mariadb:10.6
    container_name: gym-locker-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_DATABASE: gym_lockers
      MYSQL_USER: gym_admin
      MYSQL_PASSWORD: secure_password_123
    volumes:
      - ./db-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - gym-network
    command: --default-authentication-plugin=mysql_native_password

  # Mosquitto MQTT Broker (internal service)
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: gym-locker-mqtt
    restart: unless-stopped
    volumes:
      - ./mqtt-data:/mosquitto/data
      - ./mqtt-logs:/mosquitto/log
      - ./mqtt-config:/mosquitto/config
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - gym-network

networks:
  gym-network:
    driver: bridge

volumes:
  db-data:
  mqtt-data:
  mqtt-logs: 