name: "Gym Locker Management System"
version: "1.0.0"
slug: "gym-locker-manager"
description: "A comprehensive gym locker management system with RFID integration and real-time monitoring"
url: "https://github.com/Solace-Software/lockers"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
startup: services
boot: auto
init: false
hassio_api: true
homeassistant_api: false
ports:
  3001/tcp: 3001
ports_description:
  3001/tcp: "Web interface"
options:
  database_url: "postgres://user:password@localhost:5432/lockers"
  mqtt_host: "localhost"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  use_internal_mqtt: true
  log_level: "info"
schema:
  database_url: "str?"
  mqtt_host: "str"
  mqtt_port: "port"
  mqtt_username: "str?"
  mqtt_password: "password?"
  use_internal_mqtt: "bool"
  log_level: "list(debug|info|warning|error)?"